### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by Reyzadren** [kantord/LibreLingo#1017]
Requesting custom font feature so that course contributors can upload a font for the language text.
Useful for languages that don't use the Latin alphabet but has exact keyboard mapping.
Custom fonts can also be applied to any language for design purposes.

Perhaps include a folder for people to upload a font, and some documentation on how to activate or use the font.
If the questions require learners to type with the font, enable the answer automatically with the font.

**Comment by kantord** [comment]
If I understand correctly, this feature basically involves:

* Being able to include a font file with the course
* Add a feature for courses which forces the *target language* text to be rendered using the supplied font

And that's about it, right?

Another thing to keep in mind perhaps is the licensing of the font.

**Comment by kantord** [comment]
@allcontributors please add @Reyzadren for ideas

**Comment by Reyzadren** [comment]
> 
> And that's about it, right?
> 
> Another thing to keep in mind perhaps is the licensing of the font.

Yes, they are correct. Also, another optional issue is to toggle case sensitivity, but this is not important for now.

I designed my own font, but I/you/we shall just let other future contributors use their own or open-source or copylefted font.

**Comment by kantord** [comment]
>  toggle case sensitivity,

Good point! That's certainly doable too

**Comment by saeub** [comment]
Hi, sorry to stick my bib in, but this seems interesting...

> Useful for languages that don't use the Latin alphabet but has exact keyboard mapping.

I don't really understand how this helps. Do you mean you would put put non-Latin glyphs on Latin codepoints in a custom font? Wouldn't this make course development a lot more tedious (since the characters are encoded differently in the YAML/JSON files) and possibly mess up language-independent answer evaluation algorithms (e.g. when [certain Unicode characters are treated specially](https://github.com/kantord/LibreLingo/blob/2446cc1186223fbe0bb16fdf66184d8ca78dfe47/workspaces/answer-corrector/index.ts#L5-L8)). For example, it would be very confusing if a letter was unexpectedly ignored in the evaluation because the underlying character is punctuation, but the visual representation is a letter, or the other way around. Personally, I think that encouraging proper use of Unicode would be more desirable.

**Comment by kantord** [comment]
> Personally, I think that encouraging proper use of Unicode would be more desirable.

Definitely, for languages that are supported by unicode, proper use of unicode is the only recommended option

**Comment by Reyzadren** [comment]
> Wouldn't this make course development a lot more tedious (since the characters are encoded differently in the YAML/JSON files) and possibly mess up language-independent answer evaluation algorithms (e.g. when [certain Unicode characters are treated specially](https://github.com/kantord/LibreLingo/blob/2446cc1186223fbe0bb16fdf66184d8ca78dfe47/workspaces/answer-corrector/index.ts#L5-L8)).

No, I meant languages that don't use the Latin alphabet visually, but can have the same input mechanically. You're probably thinking of languages that are transliterated or transcribed from another typable script into a Latin alphabet system.

As my language does not exist, therefore, there is no unicode.

**Comment by saeub** [comment]
Okay, that's a different story then... If you have (a) a language that's not supported by Unicode and (b) there is a reasonable mapping to Unicode characters that otherwise mostly preserves Unicode semantics, I see how this could be useful.

(Just thinking out loud:) A different approach could be to extend an existing font and put your custom glyphs in private use areas. In that case, you wouldn't have to violate Unicode semantics, but you would need a custom input method, or a transliteration feature in the web app (I could see something like this be useful in a lot of other cases too, for example when an English speaker wants to learn Greek or Russian but doesn't want to learn a different keyboard layout).
