### ISSUE TITLE
Asturian for English Speakers

### ISSUE THREAD

**Issue by Siriox** [kantord/LibreLingo#1025]
Greetings Kantor and Team!
I received an email saying that LibreLingo now accepts contribution, even if now it is on an early stage. I'm not myself a coding expert but I know the basics and also have the disposition to learn.

As I understood so far on this [introductory document](https://github.com/kantord/LibreLingo/tree/master/docs/courses) it is necessary to ask the creation of a new course. I'm ready to start working on the course of Asturian for English Speakers, as my main purpose is to keep this language alive (there are no online courses at this moment). And in the future contribute with Esperanto for English & Spanish Speakers, or Asturian for Spanish & Esperanto Speakers.

I've some expertise with language courses as I was one of the first contributors on the course in Duolingo of Esperanto for Spanish Speakers (and actually I still contribute there).

Let me know what can I do to start this project.

**Comment by kantord** [comment]
Hi @Siriox amazing! I have a couple notes/questions:

- Why do you prefer starting with Asturian for English speakers instead of Asturian for Spanish speakers? If the purpose is to keep the language alive, isn't Spanish more available for the target audience? Also, consider that you might have fewer  contributors for the English one I think. Plus, Asturian and Spanish will have more in common, so creating that course might be an easier first step, which then could be used as a stepping stone for the course for English speakers. I don't want to discourage you from doing the English one of course, these are just my 2 cents! At the end of the day, it's your choice
- Is it ok if we disable audios for the Asturian course in the beginning? I need to [find a way to source audios](https://github.com/kantord/LibreLingo/issues/714) for it :smile_cat: 
- Do you foresee any specific challenges while creating the Asturian course?

**Comment by Siriox** [comment]
Hi @kantord!

> * Why do you prefer starting with Asturian for English speakers instead of Asturian for Spanish speakers? If the purpose is to keep the language alive, isn't Spanish more available for the target audience? Also, consider that you might have fewer  contributors for the English one I think. Plus, Asturian and Spanish will have more in common, so creating that course might be an easier first step, which then could be used as a stepping stone for the course for English speakers. I don't want to discourage you from doing the English one of course, these are just my 2 cents! At the end of the day, it's your choice

At first, I was thinking on greater exposure, but now that you mention that, it makes more sense to start with the course for Spanish speakers. Finally, the natural target public of the Asturleonese language is mainly inside of the borders of Spain.

> * Is it ok if we disable audios for the Asturian course in the beginning? I need to [find a way to source audios](https://github.com/kantord/LibreLingo/issues/714) for it 😸

Indeed. As you mention there, TTS right now is not suited for minoritized endangered languages like Asturian. Disable the audios is the best choice until other options appear in the future.

> * Do you foresee any specific challenges while creating the Asturian course?

Asturian alphabet uses some not so common letter as the _hache sotopuntiada_ Ḥ and the _che vaqueira_ Ḷ. They're included in the Unicode Format, but I don't know in the course itself support that option. Also, the language lacks a two-letter ISO 639-1 code (as "es" for Spanish, "ca" for Catalan or "eo" for Esperanto), although it does have a three-letter ISO 639-2 code: ast. 

Thanks again and cheers for this very interesting project!

**Comment by kantord** [comment]
> Indeed. As you mention there, TTS right now is not suited for minoritized endangered languages like Asturian. Disable the audios is the best choice until other options appear in the future.

Long term I want to have an option to upload your own audio though :wink:

**Comment by kantord** [comment]
> Asturian alphabet uses some not so common letter as the hache sotopuntiada Ḥ and the che vaqueira Ḷ. They're included in the Unicode Format, but I don't know in the course itself support that option. Also, the language lacks a two-letter ISO 639-1 code (as "es" for Spanish, "ca" for Catalan or "eo" for Esperanto), although it does have a three-letter ISO 639-2 code: ast.

Those should be fine. The special characters can be added to this list: https://github.com/kantord/LibreLingo/blob/master/courses/french-from-english/course.yaml#L14 that will create a virtual keyboard so that people who don't have an asturian input method will still be able to type them :-) Both on mobile and desktop

The language tags should also be fine. We're using IETF language tags, so `ast` is supported

**Comment by Siriox** [comment]
Those are great news @kantord! I think there are going to be no major issues for the creation in that case

**Comment by kantord** [comment]
@Siriox amazing. Let's start creating the course then? In case you need assistance, maybe we could jump on a video call?
