### ISSUE TITLE
YAML/JSON course content from an external source

### ISSUE THREAD

**Issue by diydan** [kantord/LibreLingo#1063]
**Describe the solution you'd like**

It would be great to retrieve JSON/YAML course content by calling a remote source AJAX call or otherwise.

This feature would allow the following use cases:

- Allow content/course creators to edit the content on-the-fly without having to rebuild the static frontend

- Opens up opportunities to provide content from other sources that may not have CC licensing or can not be included in the source code for other reasons licensing or otherwise.

**Additional context**
- Sometimes it simple things like image/audio/video that have licensing that would prevent it being allowed as part of the AGPL license.

- This would also allow an easier way to paywall and non-CC licensed content

**Comment by kantord** [comment]
This feature is essential because we need to be able to preview skills without having to create a new deployment.

I did some research about this.

My **hypothesis** was that:
- It is feasible to simply put a base64 or urlencoded JSON in the URL and load it from there
- there is ample room to introduce more features or longer skills in the future

This would be an amazingly simplistic solution.

In order to validate the idea, I took [the biggest JSON file we currently have](https://github.com/kantord/LibreLingo/blob/master/workspaces/web/src/courses/spanish-from-english/challenges/adjectives.json), and tried to include it in the URL. If the hypothesis is true than I should be able to include this file 10x in a URL. Either base64 or normal url encoding is permissible, as well as `lz-string` compression.

Unfortunately with the methods I tried, it's not feasible to include it even once, let alone 10x, because the URL is bigger that 32KB. Theoretically there's no size limit for URLs, but 32KB is so big that cloudflare doesn't allow it. So it can be assumed that other proxies might truncate/filter it.

So unless there's some better way to encode/compress the JSONs, it looks like the only way is to load it from an external URL :disappointed: .

**Comment by kantord** [comment]
When it comes to loading the skills from external URLs it's probably necessary to have a list of trusted URLs. Or is there a way to make it fully secure to load arbitrary URLs?

Other than the security aspect, I imagine that the URL would need to contain

- an array of links to the external JSONs to load
- an array describing a training session

The array describing the training session is necessary in order to fine-tune the training session. Currently training sessions are taking a partially randomized sample in order to create a different experience each time. For many uses cases you'd rather specify an exact training session (array of challenge IDs)

I say that it's also good to start with allowing an array of JSONs to load. This would be useful so that you can create a custom training session involving multiple different skills.
