### ISSUE TITLE
Separate course data from interface code

### ISSUE THREAD

**Issue by ftyers** [kantord/LibreLingo#114]
At the moment all of the  course data is kept in a subdirectory of the main project. It might be better to have the linguistic/course data in a separate repository from the interface code.

**Comment by kantord** [comment]
What are some of the arguments for that? How would you implement it.

Currently the entire site is statically built and this way it's really easy to build and host it. Having it in a separate repo would complicate things by a lot.

Your idea will make a lot of sense though, once the course editor is mature enough for a wide public to use it, since in that phase, building a separate backend to host the course data will be necessary, and once we're at that stage, it will also not be necessary to have the course data in a repo at all, it will be enough to maybe periodically push database dumps to a separate repo so that the course data is also available to forks.

**Comment by ftyers** [comment]
I've worked on a lot of multilingual projects, Apertium, Universal Dependencies, Matxin, DeepSpeech. It's simple to start out by just bundling everything together, but once you get to >10 languages, it becomes increasingly challenging. 

1. It's good software engineering practice to separate code from data. Example: Wikipedia, the site interface code is separated from the individual Wikipedias.
2. Everyone has to download everything, for people with good internet connections that's fine, but I've been stuck in places with very low download rates, where it would be more convenient to download 100M instead of 1G. Especially with git repositories in which clone cannot be resumed.
3. Doing this after you have a `monorepo` design is more challenging because many different things have to all come together and be extracted. 

A simple first step might be to have a separate repo for the language data and then a script to just copy the files from that repo into the main one. 

In any case, think about what will happen when you have 1000 contributors and 100 language packages, will it be more convenient to have each language course in a separate repo with its own issues page and contribution guide? I think in general decentralising course creation to communities who just need to follow an "interface" is better than having everything in one place.

**Comment by kantord** [comment]
> It's good software engineering practice to separate code from data. Example: Wikipedia, the site interface code is separated from the individual Wikipedias.

I agree. The code is pretty much separated in terms of logic already though. It is true, that the course data is currently in the same repo, but almost none of it is hardcoded.

> Everyone has to download everything, for people with good internet connections that's fine, but I've been stuck in places with very low download rates, where it would be more convenient to download 100M instead of 1G. Especially with git repositories in which clone cannot be resumed.

I assume that you are only referring to developers, not users. In the case of developers, you are kinda correct: I think it's possible to do partial pulls with git, but that would complicate things obviously. I don't intend to keep gigabytes of course data in the repo, that's for sure. But currently, the entire code is 8MB in a ZIP file, which should be manageable. We are relatively far from this becoming a problem.

> Doing this after you have a monorepo design is more challenging because many different things have to all come together and be extracted.

The project is in a very early stage and with the current repo structure it's possible to make changes to course data structure and implement them in the frontend code in a single merge request. That's a huge benefit, since such changes are still being made frequently. If any tiny change to the data structures needed a coordinated effort between multiple repos, that would make things much more difficult. Once the data structures are more stabilized, we can start thinking about such things.

I am not against having multiple repos in general, I just don't want to over-engineer things in a way that can sabotage us.

**Comment by ftyers** [comment]
> I agree. The code is pretty much separated in terms of logic already though. It is true, that the course data is currently in the same repo, but almost none of it is hardcoded.

Good to hear!

> > Everyone has to download everything, for people with good internet connections that's fine, but I've been stuck in places with very low download rates, where it would be more convenient to download 100M instead of 1G. Especially with git repositories in which clone cannot be resumed.
> 
> I assume that you are only referring to developers, not users. In the case of developers, you are kinda correct: I think it's possible to do partial pulls with git, but that would complicate things obviously. I don't intend to keep gigabytes of course data in the repo, that's for sure. But currently, the entire code is 8MB in a ZIP file, which should be manageable. We are relatively far from this becoming a problem.

Mostly developers, I guess most users will not be downloading the whole repo. But in any case it makes sense to try and keep the size down. I remember being in rural Mexico last year and trying to make an Android keyboard without having the Android SDK downloaded already. It was impossible to download 3G there given the connection quality/stability. 

> > Doing this after you have a monorepo design is more challenging because many different things have to all come together and be extracted.
> 
> The project is in a very early stage and with the current repo structure it's possible to make changes to course data structure and implement them in the frontend code in a single merge request. That's a huge benefit, since such changes are still being made frequently. If any tiny change to the data structures needed a coordinated effort between multiple repos, that would make things much more difficult. Once the data structures are more stabilized, we can start thinking about such things.

Sounds good to me. 

> I am not against having multiple repos in general, I just don't want to over-engineer things in a way that can sabotage us.
> 
> edit: regarding "extracting" things, much of the code can still be developed as if it was separate repos. That's more or less the approach I'm trying to keep in mind anyway.

That's great to hear! 

How about leaving this issue open and then looking into it again once more courses are added? When it has stabilised a bit more I wouldn't mind starting to add Catalan and Turkish.
