### ISSUE TITLE
Properly document mini dictionary

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#1145]
**Is your feature request related to a problem? Please describe.**
As @adnan360 [said](https://github.com/kantord/LibreLingo/pull/1121#issuecomment-786950458):

> About the missing definitions, I felt that documentation was not helping me understand what I'm supposed to do. 

**Describe the solution you'd like**
There is a clear, precise and short explanation in this file: https://github.com/kantord/LibreLingo/blob/main/docs/courses/editing-courses.md

**Describe alternatives you've considered**
I've considered changing the way how the mini-dictionary works. For example moving it to separate
files and not requiring all definitions to be present.

These options could me more problematic, because it could lead to other problems such as missing definitions.
Also, having to edit only 1 file to update just one skill is making things a lot simpler.

So first let's try to work with this.

**Additional context**
This is kind-of documented already: https://github.com/kantord/LibreLingo/blob/main/docs/courses/editing-courses.md#by-example

But looks like this documentation is not clear enough.

**Comment by adnan360** [comment]
The existing text is ok but I think:
- it barely touches on what's absolutely needed
- not detailed, not well explained, especially the YAML keys and how they work
- assumes the user has enough understanding already of how the course system works
- it's hard to understand and navigate for new contributors

I think all the documentation in this project, especially which are related to course contribution should be detailed, informative and geared towards more novice users so that it's easy for anyone to contribute.

An example snippet would be:

---
# LibreLingo Course Contributors Guide

Thank you for your interest in contributing courses to LibreLingo. This document has guides for both creating new courses and editing or translating existing courses. ... ... If you have any questions that are not clear feel free to [post an issue](https://github.com/kantord/LibreLingo/issues) or send an email to: ...
...

## Terminology

In a nutshell:

- A **Course** is a set of modules. There is typically one course for each language. e.g. `spanish-from-english`, `french-from-english`.
- A **Module** is a set of lessons. They act like groups to keep lessons more organized.
- A **Skill** is a lesson with a set of questions.

So the hierarchy would be: `Courses > Modules > Skills`

On the `courses` directory of [this repository](https://github.com/kantord/LibreLingo/) you will find courses. Under each course you'll find modules. And inside each module you'll find skills as individual yaml files.

"Courses" are listed on the homepage and there are courses for each language. You can think of courses as languages if that's more comfortable to you.

"Modules" are listed inside, when you enter a course page, as headings. And under each heading there are a list of skills.

"Skills" are actually lessons focused on a particular subject. Each skill is like a set of questions with a particular theme. For example, "Animal" skill has questions relating to animals, "Food" skill has questions related to foods. Each skill is designed to test the skill on a certain topic.

Inside a skill YAML file there are some keys that you might want to learn of. ...

## Translating existing courses

Note: If you are new to contributing skills, these are the things you can do to get a proper understanding and have a good time with the project:
- Go to [LibreLingo's Spanish course](https://librelingo.app/course/spanish-from-english) and try out some of the skills. Just get an idea on how the questions are phrased and the type of answers made available.
- Clone this repository or download it and study the `courses` directory and how everything's laid out. Be sure to have a good text editor, such as Notepad++, Geany in hand to view or edit files.
- Try to learn how data is organized within files and directories.
- Try to learn how YAML works. (see [here](https://blog.stackpath.com/yaml/) or [here](https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started/))
- Determine some information about your language.
  - Your language name. e.g. French, Ancient Greek
  - Language slug (lowercase and no spaces). e.g. french, ancient-greek
  - IETF BCP 47 tag name for your language, which you can get from [here](http://www.iana.org/assignments/language-subtag-registry). Just look for the `Subtag`. e.g. fr, grc
- If you have questions, send an email at: ...
...
### Translating based on existing course
For a typical basic use case, you can start any course by copying an existing course. For example,
- go to `courses` directory on the repository you downloaded
- copy `spanish-from-english` and rename the copy as `yourlanguageslug-from-english`
...
## Contributing new courses

Beginners should not be bothered by this section. This section is for those who want to create new courses from scratch, which is for those who have sufficient understanding of the project and how the courses work. But you may continue at your own discretion.

WARNING: If you just want to make any existing course to be available on your language, please refer to the "Translating existing courses" section above and ignore this section.
...

---

**Comment by kantord** [comment]
Hi @adnan360, do you want to create a pull request with this change? Then I can use proper code review tools to make suggestions and we can merge it :wink:
