### ISSUE TITLE
Create a very easily installable binary version

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#1175]
**Is your feature request related to a problem? Please describe.**
Sometimes a school or other organization might want to set up their own local server. They need an easy way of installing a server that doesn't involve having to read the documentation.

**Describe the solution you'd like**
- The solution should be cross-platform
- You should not need to have nodejs/npm/etc installed in order to install the binary version

Some tech information:

Here's how you export the whole page into a static site: https://github.com/kantord/LibreLingo/blob/main/.semaphore/pipeline_2.yml#L20

This is already done there in the CI, so basically this package could be built in the same CI step, utilizing the already existing static site.

A very simple, no-setup static site server can be used to serve these files on a local network. Here's one example: https://www.npmjs.com/package/serve

So this issue is mostly about figuring out how to package those things in a way that it becomes very easy to install, or even just a single executable on windows

**Comment by kantord** [comment]
It is actually probably a good idea to *not* use anything nodejs based. The reason is, the static site doesn't depend on nodejs at all. It's probably difficult and impractical to package a nodejs app into a single executable in a way that the user doesn't have to install nodejs.

		It's probably better to use something like Go or Rust to somehow build the static files _into_ a server executable.

**Comment by dhelmr** [comment]
Hi, it seems that using go with [pkger](https://github.com/markbates/pkger) could work for this. I can give it a try.

**Comment by kantord** [comment]
@dhelmr that sounds amazing!

Feel free to create your Go project in a subdirectory in this folder: https://github.com/kantord/LibreLingo/tree/main/apps

In order to automate the building and publication of the package with the most up-to-date data, you can probably extend this CI pipeline. It already builds the static HTML files and other assets

**Comment by kantord** [comment]
btw it's also worth researching if there are any practical size limitations on actually creating a single executable.

maybe it'll be more practical long term to have one executable _per course_. Albeit even in that case it's probably a reasonable first step to start with just one executable :-)

**Comment by dhelmr** [comment]
Alright, I will look into it. Feel free to assign the issue to me :) 

Using the internal go http server together with pkger works flawlessly for me locally (results in an executable file of ~50MB). Regarding executable creation for different platforms and the CI integration I need some more time; I will probably post an update towards the end of the week.

> btw it's also worth researching if there are any practical size limitations on actually creating a single executable.

According to [this thread](https://superuser.com/questions/667593/is-it-possible-to-run-a-larger-than-4gb-exe), Windows won't support anything larger than 4GB for an `.exe` file. However, I think the go+pkger solution would run into performance issues long before that. So, scalability is probably something to keep in mind. But I agree that for simplicity, it should be enough to start with one executable for now.

**Comment by kantord** [comment]
> Alright, I will look into it. Feel free to assign the issue to me :)

Cool, just did!

> Using the internal go http server together with pkger works flawlessly for me locally (results in an executable file of ~50MB).

amazing!

> According to this thread, Windows won't support anything larger than 4GB for an .exe file

Amazing, 4GB is pretty big, I think it will be big enough for a long time

**Comment by dhelmr** [comment]
I just made a PR containing a first draft for this. The binaries are built in Semaphore and released as artifacts there. 

Some things I'd like to discuss:

* The binaries are built by a bash script atm, which is kind of hacky. Something like a Makefile or integrating it into the already-existing packaging systems maybe would be better, but to be honest I do not have much experience with that
* The login/sign in buttons do not work, because the links point to `librelingo.app` and the browser blocks them. Should the login system be managed by the go server as well? 
* There is no SSL support atm. Do you think it is needed? There are dedicated tools for this anyways, and, for me, it doesn't feel like it would belong to this project.
* The binary is intended to be started from the CLI (especially if the port and/or binding address should be modified). On Windows, you can still double-click the file and it runs; however, a little GUI, where those options can be entered, might be more user-friendly. But that's probably something for a future PR, if at all.
* Should there be any integration tests for the resulting binaries?

**Comment by kantord** [comment]
> The binaries are built by a bash script atm, which is kind of hacky. Something like a Makefile or integrating it into the already-existing packaging systems maybe would be better, but to be honest I do not have much experience with that

I think the bash script is ok for now. I don't have any experience with Go build systems. We could add a Makefile, but the added value would be relatively small at this point. We can refactor it later

**Comment by kantord** [comment]
> The login/sign in buttons do not work, because the links point to librelingo.app and the browser blocks them. Should the login system be managed by the go server as well?

Not yet. I'm not sure what would be the solution to make the login system work.

**Comment by kantord** [comment]
> There is no SSL support atm. Do you think it is needed? There are dedicated tools for this anyways, and, for me, it doesn't feel like it would belong to this project

Not needed, I think the main usecase for this would be running it on a local network in a school with poor internet connection for example

**Comment by kantord** [comment]
> The binary is intended to be started from the CLI (especially if the port and/or binding address should be modified). On Windows, you can still double-click the file and it runs; however, a little GUI, where those options can be entered, might be more user-friendly. But that's probably something for a future PR, if at all.

Yup, future PR

**Comment by kantord** [comment]
> Should there be any integration tests for the resulting binaries?

If you can prepare a separate pull request for that, it would be nice!

**Comment by kantord** [comment]
> Should the binaries be published on github?

I would say so, either GitHub packages, or just copying them to gh-pages 

As per versioning, I guess it's possible to figure out the version from apps/web/package.json somehow? But it's a good question, how to do that long term... as most updates to this package will be due to simple content updates... Maybe it would be a good idea to simply use something date and time based for versioning?

**Comment by dhelmr** [comment]
> Not yet. I'm not sure what would be the solution to make the login system work.

Hm, maybe this could be indicated somehow in the website served by the go server? Currently, when someone tries to register there, the page just loads forever without any error message shown, while a login fails with `TypeError: NetworkError when attempting to fetch resource`. Or would it be possible to remove the login/register buttons completely?

> If you can prepare a separate pull request for that, it would be nice!

Okay, I might look into that. But it won't be too near in the future in any case probably :) The idea is that already-existing tests for the web interface (if there are any) could maybe executed with the standalone server as well, so that things like the non-functioning login system can be found.

> As per versioning, I guess it's possible to figure out the version from apps/web/package.json somehow? 

Yes that should be possible.

>  But it's a good question, how to do that long term... as most updates to this package will be due to simple content updates... Maybe it would be a good idea to simply use something date and time based for versioning?

Maybe a combination of both of them (version+commit timestamp)? Another question would be how to manage updating the files with an increasing executable size. Currently the binaries are around 50MB, so downloading it again for a minor change in a course might be acceptable, but probably not when it has a size of 500MB. The binary extracting the web files somewhere and checking for updates automatically could solve this, but I'm not sure if this already introduces too much complexity.

**Comment by kantord** [comment]
> Hm, maybe this could be indicated somehow in the website served by the go server? Currently, when someone tries to register there, the page just loads forever without any error message shown, while a login fails with TypeError: NetworkError when attempting to fetch resource. Or would it be possible to remove the login/register buttons completely?

let's create a new issue for this. I think it's possible to make the buttons disappear on localhost unless you are running the development server

> Okay, I might look into that. But it won't be too near in the future in any case probably :) The idea is that already-existing tests for the web interface (if there are any) could maybe executed with the standalone server as well, so that things like the non-functioning login system can be found.

Maybe it's enough to test the static website with any other server? One issue I see is that in the end to end test, we either have to mock the login system or launch a test server in order to test it. That's because it's not a good idea to let it call the production server and register thousands of users that will never actually be used.

The main reason the login system doesn't work in localhost is CORS. If you open it in a browser that doesn't have CORS it should work I think. One possibility to make the login system work properly is to extend the go server so that it can _proxy_ requests to the login system through itself, so that your browser can hit localhost which will be allowed by CORS

**Comment by kantord** [comment]
> Maybe a combination of both of them (version+commit timestamp)? Another question would be how to manage updating the files with an increasing executable size. Currently the binaries are around 50MB, so downloading it again for a minor change in a course might be acceptable, but probably not when it has a size of 500MB. The binary extracting the web files somewhere and checking for updates automatically could solve this, but I'm not sure if this already introduces too much complexity.

Yes, version + timestamp sounds good too!

Regarding updates, I think that's ok. The point of this is easy usage in a school or other environment without much technical knowledge. So probably most people who use this, won't care to update it every day. So probably adding a GUI instead of the terminal app for instance would be a much bigger help to many people I imagine.

If someone really wants to run their own server and have the hardware and technical knowledge to maintain it, then they could always just git clone, install nodejs and run `yarn install` and `yarn start`
