### ISSUE TITLE
Multi-word mini-dictionary terms

### ISSUE THREAD

**Issue by zmbc** [kantord/LibreLingo#1450]
Right now, each *word* in a `Translation` must have a definition in a `Mini-dictionary`. In other words, the `Translation`s are split on the space character to break them into chunks.

But this is not always the best way to split them, pedagogically. Certain phrases are more relevant to the lesson at the phrase level -- e.g. "post office" or "land animal" or "blue whale" -- especially when that concept is represented in the target language by a single word, or a completely different compound phrase. In that case, being able to look up the words "blue" and "whale" separately is no help at all.

Therefore, a useful feature would be able to manually override the behavior to join certain multi-word terms into single mini-dictionary entries. @kantord [suggested](https://github.com/kantord/LibreLingo/issues/1445#issuecomment-880815451) curly braces around the phrase, e.g. `{post office}`. These would be underlined together, and mousing over them would bring up a single tooltip with the corresponding translation of the phrase.

I am happy to tackle implementing this feature.

**Comment by kantord** [comment]
I think this can be implemented relatively easily by changing this line:

https://github.com/kantord/LibreLingo/blob/0448295e71fd2e0b8b6190f067c90a0e80586f3b/apps/librelingo_json_export/librelingo_json_export/dictionary.py#L63

Although it's possible that other lines will have to be changed as well, in order to make sure that the curly braces don't show up in the final files.

Also, it probably makes sense to also make it so that `{post office}` will become a single chip in chip challenges? In that case, you'll also have to change the implementation here: https://github.com/kantord/LibreLingo/blob/main/apps/librelingo_json_export/librelingo_json_export/challenge_types.py#L71
