### ISSUE TITLE
[Idea] Learn declensions

### ISSUE THREAD

**Issue by airon90** [kantord/LibreLingo#175]
I know you are thinking about creating a platform for learning words.
I would like to have the possibility to learn grammar skills.
Example, I'd like to learn declensions of words.
[I wrote](https://github.com/airon90/learnDecl) a script which works in terminal and gives me some exercises to test my Finnish skills.
If you want, you can use it somehow :)

**Comment by kantord** [comment]
> I know you are thinking about creating a platform for learning words.

Actually no, my intention is to create a platform for complete language courses with grammar being included. I am actually actively working on an exercise type that is solely aimed at grammar practice: https://github.com/kantord/LibreLingo/pull/173 (word order/sentence structure in this case). What gave you the idea that it's only about vocabulary? Perhaps something in the documentation should be improved :smiley_cat: 

I am *definitely* intending to include things to learn and practice declension with (or any other form of inflection). I don't really believe in the approach of practicing it in isolation, for two main reasons:

- I think it's not fun, and the main reason people don't learn a language is that they give up because they are not having fun
- It also lacks context, so I think that it doesn't aid memory as much as practicing with context, and perhaps doesn't improve fluency as fast either (citation needed :smiley_cat: )
- It is quite hard to create a system that universally works for all languages, since each language has it's own quirks, so a system that focuses on learning by example (and explanations) would also have the advantage of being more universal

By learning by example I mean, that the same word would show up in different forms throughout the course, and there would be explanation as to why and how that happens. (Pluralization rules, grammatical gender, etc.) 

That being said, I think a tool like the one you linked is very useful, and definitely something that many (if not most) learners would use at least at some point in their journey to fluency. The approach I see most useful for such tools is to not integrate them as an essential part of the main course. Rather, LibreLingo could work together with other (existing or new) free software/open source projects and give a milder level of integration with such tools. For example, such a tool might be added as a plugin or simply linked at the relevant lessons.

What do you think? Do you think this approach can work?
