### ISSUE TITLE
replace "".format() calls with f-strings in the Python code

### ISSUE THREAD

**Issue by szabgab** [kantord/LibreLingo#1883]
There are already a few f-strings that will set a minimum requirement of python. Using f-strings everywhere makes the code more readable and standardized.

**Comment by kantord** [comment]
Good idea. I think some linting rule should be added for this so that it does not depend on human code review and such.

**Comment by kantord** [comment]
So I installed pylint in order to enable checking this. Unfortunately the state of the code style according to pylint is abismal so I had to disable most rules. The reason I did it is because I only want to have rules enabled that we actually intend to enforce. So rules that are not enforced yet should be disabled and should be re-enabled later.

For this very example, I enabled the rule and fixed the code issues in #1893
