### ISSUE TITLE
Don't count missing punctuation as "small mistakes"

### ISSUE THREAD

**Issue by slesingerm** [kantord/LibreLingo#349]
Currently, if a sentence in "learn a new sentence" is written with punctuation marks, the app will show a "small mistake" message if the user writes the sentence without punctuation.

I'd suggest to remove this and not count punctuation as "mistakes" at all.

**Comment by kantord** [comment]
This has to be fixed in this file: https://github.com/kantord/LibreLingo/blob/master/workspaces/answer-corrector/index.js

However, I'd say that punctuation is important... I would maybe just rather be a little bit more tolerant with it: for example allow skipping a full stop at the end of the sentence. Or perhaps only warning about this when there is more than 1 punctuation missed in the sentence
