### ISSUE TITLE
Translating platform

### ISSUE THREAD

**Issue by aha999** [kantord/LibreLingo#56]
I'd recommend [Weblate ](https://weblate.org/)as a translating platofrm for the community to translate any part of the platform / app, strings, words etc. Many opensource projects, apps etc. use it and Weblate itself is [opensource ](https://github.com/WeblateOrg)and you can host it yourself if you wanted to. For Opensource projects, the use of Weblate is completely free and hosted by them, you just need to write a form to request their hosting of the translations for the platform on the [Hosting page](https://weblate.org/sl/hosting/) ([gratis Plan](https://hosted.weblate.org/hosting/)). Then you can put a translation progress widget to github page so anyone can see the progress of language translations and click it to translate.

**Comment by kantord** [comment]
Thanks! This will become relevant once another course is being developed, that has a different source language. (For example, English for Spanish speakers).

**Comment by roptat** [comment]
Please notify me when this is ready :). Note that you want to have a translation before course content: English learners who speak Spanish will need the website in Spanish so they understand how to start the English course for Spanish speakers for instance.

**Comment by aha999** [comment]
Exactly, and so they can  navigate through it in their own language. I'd say it'd be best if he made a request now and have the platform ready to at least get the website specific translations.

**Comment by airon90** [comment]
I can translate the platform in Italian and Esperanto

**Comment by aha999** [comment]
I can translate to Slovenian.

**Comment by navanchauhan** [comment]
What about Transifex https://docs.transifex.com/projects/open-source-project

**Comment by roptat** [comment]
Having tested both, weblate is handling the community aspect of translation better I think, but I would help on either platform (or any platform really, there are so many!). I also think it makes more sense for the project to use a free software, self-hostable solution that a plaftorm from a private company you have no way to change or influence.

**Comment by kantord** [comment]
An update here.

I set up translation and translated the landing page: https://github.com/kantord/LibreLingo/commit/aab34fbdcc5ed90c010262165247ac29e9036022

It cannot be considered fully done, since there are currently only courses for English and no way to change the interface language. That will come once there will actually be courses with source languages other than English.

I tried this platform for translations and so far it seems to serve it's purpose well: https://poeditor.com

**Comment by airon90** [comment]
Thank you very much for your work!
As I have spare time just now, I started translating in Italian #156 and in Esperanto #158 (and fixed a typo in English #159)
I'm looking forward to starting a non-English course (it ←→ eo) ;)

**Comment by kantord** [comment]
Thank you! I merged them + added you to contributors + imported the translations to POEditor.

I also added you to POEditor as a contributor so that you can submit new translations without creating PRs.

_I am closing this this issue as there's not much that can be done at this point, the things that were priority are already done_

(Feel free to reopen with comments if you disagree. I'll think about what new issues could be opened regarding translation)

Regarding adding a new course: we might have to wait with that, as the very least I want to develop a course further so that we have a model to follow with the other courses :-)

**Comment by roptat** [comment]
before closing, please add a link to the readme and website so we know where to contribute. By the way, poeditor doesn't seem to have a search field or anything like that. How do I contribute?

**Comment by kantord** [comment]
Fair enough! Here it is, @roptat: https://librelingo.readthedocs.io/en/latest/translation/

**Comment by airon90** [comment]
@kantord Info about LibreLingo are not translatable

**Comment by kantord** [comment]
@airon90 are you referring to the markdown thing? The page that has the same text as README.md? That is not meant to be translatable. Instead, on the long term, it should be replaced with a fancier page built just for this purpose, and that should be translatable. 

I created a new issue for that: https://github.com/kantord/LibreLingo/issues/166
