### ISSUE TITLE
Tell Cypress to wait for fonts before taking screenshots

### ISSUE THREAD

**Issue by doamatto** [kantord/LibreLingo#608]
**Is your feature request related to a problem? Please describe.**
Not an inheirt problem for the end-user, but makes CI checks fail

**Describe the solution you'd like**
Whenever a PR or commit is made and the star count has changed since the last time Percy has seen it, it'll fail CI because of a visual error. It would be nice for this not to happen so Percy reports are meaningful and not an issue with star counts.

**Describe alternatives you've considered**
N/A

**Additional context**
[Example of these issues via Percy](https://percy.io/LibreLingo/LibreLingo/builds/6437576). See the `listening challenge` and `the terms of service page` for prime examples

**Comment by kantord** [comment]
I would say it's rather due to the fonts not being properly loaded.

To solve this we should ideally look for ways to wait for the fonts to be properly loaded before the screenshot is being taken.

If that doesn't work out, we should take inspiration here: https://github.com/palmerhq/cypress-image-snapshot/issues/18 i. e. basically forcing a locally available font in Cypress, instead of the correct font used in production.

**Comment by kantord** [comment]
@allcontributors please add @doamatto for bug

**Comment by kantord** [comment]
fixed here https://github.com/kantord/LibreLingo/commit/5b5be67d660ffd4e55261822b7d9ce7ca01336bf
