### ISSUE TITLE
federation of social features through ActivityPub

### ISSUE THREAD

**Issue by wakest** [kantord/LibreLingo#65]
I just found out about this project through a [friend posting about it on the fediverse](https://chaos.social/@pinkprius/103618677259618401) and I also made a post [about it right after](https://social.wake.st/@liaizon/103624887716630030). I have a specific interest in building a language learning project that would federate its social aspects (like the shared leader board that duolingo has, and maybe sharing some sort of daily streak activity) with the fediverse. I have been talking to people about this for over a year now and have had a number of people message me that they were interested in this idea as well.

[ActivityPub](https://www.w3.org/TR/activitypub/) link if you are not familiar with it.

Not sure if this is out of scope for this project, but if you were interested in LibreLingo being social at all please think about the fediverse as a base to build upon. And I along with many others on the fediverse are very excited about this project and want to help and contribute regardless.

**Comment by swift2plunder** [comment]
The shortest path to sharing courseware would probably be to leverage an existing open source courseware server. There is a courseware server, based on a fork of Pleroma that (last I checked) had federation on its roadmap. I need to fact check myself on the status of federation in that project, but if you're open to leveraging an existing server application for the backend, I'll verify the details and help with the client protocol

**Comment by kantord** [comment]
This is definitely an idea that I would like to experiment with.

There's 2 things I would like to emphasize:

- LibreLingo should be safe for everyone, even small children for example. Social features should focus on things that don't need to be moderated and don't give a platform for cyber-bullying.
- I want LibreLingo to be very future-proof, so I'd try to avoid adding features that would require server infrastructure to be maintained, or things that depend on 3rd party things. It will probably not be possible to avoid that completely, but it is still something to think about.

With those things in mind, I'm very open to discussing any specific ideas about how the social features would look!

**Comment by kantord** [comment]
@all-contributors please add @wakest for ideas
@all-contributors please add @swift2plunder for ideas

**Comment by kantord** [comment]
@all-contributors please add @swift2plunder for ideas

**Comment by kantord** [comment]
@all-contributors please add @wakest for ideas

**Comment by sebilasse** [comment]
@redaktor is interested in helping. Talked to @wakest via ActivityPub before ;) :
What we would like to achieve is a safe collaborative translation UI.
I'd like to answer your two bullet points directly

> LibreLingo should be safe for everyone, even small children for example. Social features should focus on things that don't need to be moderated and don't give a platform for cyber-bullying.

I think "safe for everyone"  is the same for the ActivityPub projects which would help.
It should be pluggable and configurable.
That means the users should hand out keys just to the users they trust.
So I encourage to read https://gitlab.com/spritely/ocappub - it would be a journey.
However : I agree that this point is a MUST.

> I want LibreLingo to be very future-proof, so I'd try to avoid adding features that would require server infrastructure to be maintained, or things that depend on 3rd party things. It will probably not be possible to avoid that completely, but it is still something to think about.

This is **exactly** how ActivityPub was initially thought and it requires to use the Client2Server portion of the spec. 
You have a thin, generic ActivityPub server. 
As long as it follows the specifications [ActivityPub](https://w3.org/TR/activitypub/), [ActivityStreams](https://w3.org/TR/activitystreams-core/), [ActivityStreams Vocabulary](https://w3.org/TR/activitystreams-vocabulary/) we only need to define some special LD things and then it would be a client-only thing.
And here we could simply start with a UI wich understands ActivityPub objects.

**Comment by swift2plunder** [comment]
First, nothing is safer than offline. As a homeschooling parent, there have been times in my child's life when that was very important to our family. We can definitely keep CouchDB as the local datastore and make replication over the internet optional, preserving that desirable feature. The moderation profile of the Fediverse provides a lot of latitude for expression on connected services and complete autonomy of services with regard to moderation. So the contents of the global feed is entirely in the hands of the local moderation team. Moderation policy is the main point of differentiating servers, and several options for self hosting are available. I would add that the additional complexity of creating an account on a distributed service would be a compelling reason to preserve an account-free onboarding workflow

ActivityPub is a w3g recommendation that extends ActivityStreams 2.0 with CRUD semantics, the actor model, and several other standard collections for profiles. It also establishes a pattern of using JSON-LD to provide those features to any semantic vocabulary. One characteristic of the protocol over the network is that extensions are treated as a black box by intermediaries, so unknown extensions are transmitted without being altered or deleted. So LibreLinguo, as an ActivityPub client, should be able to connect to Pleroma or another ActivityPub server offering AP C2S and use it as remote store to save a backup of progress and optionally to federate social or gamification features. The client could be perfectly functional even in a moderation free COPPA compliant mode where no free text from the network is rendered in the UI, if desired.

The extent of collaboration with server developers required for the client to "just work" is that the AP C2S must be offered and enabled on the target server and the client must be able to acquire permissions to create the collections and other objects required by the application, which may also involve creating an OAuth2 scope

By leveraging a w3c specification used on multiple servers (though not the more popular ones, for historical reasons) you fully externalize the maintenance of server infrastructure without being dependant on any one project or vulnerable to development churn. Moreover, object capabilities and other security policies would be administered at the server level

So that leg work I promised... I'll start in tonight

**Comment by swift2plunder** [comment]
MoodleNet is currently testing federation. Moodle and CommonsPub use GraphQL for their client API

Currently, Pleroma and NextCloud expose ActivityPub C2S interfaces as servers. For the most part, AP C2S is just a set of JavaScript over http envelopes for getting messages from an inbox and posting to an outbox, but a lack of opinionated libraries has hurt development

I've written an AP library for Lua (which might be viewed as incomplete because I haven't supplied an application yet to show how an opinion might be applied) that relies on features also available in JavaScript. For the sake of opening up the ecosystem, and not this project alone, I'm looking at preparing a JavaScript implementation that sufficiently opinionated to be immediately useful

**Comment by swift2plunder** [comment]
Moodle (courseware) is currently testing federation. Moodle and CommonsPub use GraphQL for their client to server protocol and federate using ActivityPub

Servers offering ActivityPub C2S include NextCloud and Pleroma. I'm looking at writing a C2S client library just so JavaScript developers can find one on github, but it's scarcely necessary

AP is just a JSON envelope. It isn't complicated to implement for a client with a specific purpose. It's reputation for being maddeningly difficult comes from trying to generalize an implementation and from poor findability of coherent implementation guidance. I'm working on the guidance 😎

**Comment by aschrijver** [comment]
Heads up, as this is on the agenda of the next [SocialCG meeting](https://socialhub.activitypub.rocks/t/2020-04-25-socialcg-meeting/625).

**Comment by decentral1se** [comment]
Related: https://github.com/kantord/LibreLingo/issues/416.

Also, I guess, it is worth noting that projects like https://little-boxes.readthedocs.io give you the shell of what you need to communicate with the protocol and leave the back-end to you. That might be an approach to get __something__ on the fedi to start with without having to implement the full stack. I guess you'd just plug your data model in and expose the end-points.

**Comment by aschrijver** [comment]
Looks like there is a lot of interest for ActivityPub support. Is there any chance that this becomes part of the roadmap? Are contributors wanted/required for this (I can do a shout out on [Humane Tech Community](https://community.humanetech.com) channels)?

**Comment by kantord** [comment]
@aschrijver based on the little I know about ActivityPub, I really like the idea! My biggest priority right now is the course editor, but it could definitely become part of the roadmap. Also, you are free to submit PRs any time :-)

I know very little about ActivityPub, so I'm not completely aware of how this would work. I think what we'd need:

- A rough outline of the technical implementation
- A rough design of the simplest ActivityPub-based features users would find useful and enjoy
- Assessment of any hosting extra costs or regular duties/responsibilities

Based on such information I can give you feedback on whether there are any feasibility issues we need to solve, and also give you feedback on how _I_ can help with it.

Does that make sense?

> Are contributors wanted/required for this (I can do a shout out on Humane Tech Community channels)?

Definitely!

**Comment by aschrijver** [comment]
Thanks for the info (started with this [toot](https://mastodon.social/web/statuses/104936763523217909). And adding pointers to [Guide for new AP implementeres](https://socialhub.activitypub.rocks/t/guide-for-new-activitypub-implementers/479) on SocialHub, and Feneas [AP watchlist](https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps) and [AP developer watchlist](https://git.feneas.org/feneas/fediverse/-/wikis/Watchlist-for-ActivityPub-developer-resources).
