### ISSUE TITLE
Help: how to open course editor to more people?

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#711]
## Problem statement

While the course editor is fully functional and makes it easy to edit the course content, it does not facilitate collaboration sufficiently. It's not enough to draw in a wealth of contributions, it's also extremely important to maintain an efficient, sensible, and fun course structure. To do this, the course editor would probably need to enforce some sophisticated constraints, and also have a way to determine who can approve content.

## Some ideas

Extend Django Admin with the required functionality. Or perhaps use Django to create a GraphQL or REST API, and build a custom frontend on top of that for the course editor. Perhaps move to a document store model for the course editor. Perhaps let some people experiment with course content being stored in a git repo for a specific course. Or try using a MediaWiki instance? **What do you think about these ideas?**

I already have a [proposed solution](https://github.com/kantord/LibreLingo/issues/377), however it might be rather tough to implement. Ideally, we'd have a solution that can be broken up into small tasks.

**Comment by garrison** [comment]
> While the course editor is fully functional and makes it easy to edit the course content, it does not facilitate collaboration sufficiently. It's not enough to draw in a wealth of contributions, it's also extremely important to maintain an efficient, sensible, and fun course structure.

Well said.

> To do this, the course editor would probably need to enforce some sophisticated constraints, and also have a way to determine who can approve content.

In all honesty, it will be very difficult for you to predict in advance what these "sophisticated constraints" ought to be.  The desired constraints will necessarily evolve and require iteration over time, as you learn what does and does not work for both enabling collaboration and keeping learners engaged.  I fear that coding these into the course editing system will create a high barrier to having this workflow evolve.
> [...]
>
> Or try using a MediaWiki instance?

When we started the [Wikiotics](https://wikiotics.org) project, we were inspired heavily by Wikipedia.  My initial collaborator, @wikey, spent a lot of time evaluating the software on https://www.wikimatrix.org/, hoping to find a wiki engine that we might easily extend to work well with interactive language lessons.  After much consideration, we felt that no existing wiki software was built to enable collaborating on truly structured content, so we created our own wiki engine, [Ductus](https://github.com/wikiotics/ductus).  (We used Django as a framework, but we did not build on the Django admin interface.)  Our rationale for creating another wiki engine can now be found [on the Wayback Machine](https://web.archive.org/web/20160219073512/https://code.ductus.us/).

We never had the resources to realize our vision with Ductus.  I believe now that a much more reasonable path forward is to have a static site (we are now using Hugo; LibreLingo could use Sapper, as it already does), and create a simple editor for the actual course content that works in the browser and helps the user prepare a change which is ultimately reflected as a pull request on GitHub.  I have some thinking about how we might do this at https://github.com/wikiotics/wikiotics.org/issues/16 and https://github.com/wikiotics/wikiotics.org/issues/15.  While the heavy lifting of actual lesson content can be done in a GUI editor, the structures to tie together lessons would be specified by code (e.g. json or toml), and the "sophisticated constraints" you mention can then be enforced during code review, rather than having sophisticated GUI code to enforce them.  Simpler here is better, as the desired structures will evolve over time.

**Comment by kantord** [comment]
@garrison, thanks for you detailed comment, it's really helpful to read about your experience with Wikiotics.

> In all honesty, it will be very difficult for you to predict in advance [...], The desired constraints will necessarily evolve and require iteration over time, [...]  I fear that coding these into the course editing system will create a high barrier to having this workflow evolve.

I think that's a very valid concern. If we can build such constraints, we should strive to build them in a way that leaves us free to do changes to the constraints without having to do complicated database migrations.

I imagine, for example, creating constraints at form validations, or constraints that show up as warnings, etc.

> so we created our own wiki engine, Ductus.

Do you think Ductus could be used as a course editor for LibreLingo? And by the way, did you experience any issues or challenges with the maintenance or use of Ductus?

> create a simple editor for the actual course content that works in the browser and helps the user prepare a change which is ultimately reflected as a pull request on GitHub. 

This is actually the first option I considered, I like the idea a lot for it's simplicity. But I have one major concern: how do you deal with conflicts? Even if your course is built with very small units (small JSON files), potentially multiple people could be changing the same file at the same time.

I don't think there's an automatic way to resolve arbitrary conflicts automatically, and even if it was, it would also have to be orchestrated in some way automatically...

One way around that would be perhaps to automatically merge the changes to the main branch, and have a queue and "lockfiles" in place, but that also doesn't seem like an idea solution

**Comment by wikey** [comment]
> But I have one major concern: how do you deal with conflicts? Even if your course is built with very small units (small JSON files), potentially multiple people could be changing the same file at the same time.

Let git worry about it. If the files are small enough, then the conflicts will be easy to resolve. And, if lots of people are simultaneously working on the same small part of the course, then the main problem is likely to be a collaboration/coordination one rather than something you can solve technically. Think about Wikipedia's WikiProjects, which are entirely focused on coordinating and consensus building as a separate layer on top of the technical work of editing Wikipedia pages. If you have three editors all working on the same page of a large book, the easiest solution is to avoid the problem by having a way for them to decide ahead of time who should work in which section that day so they can all get something productive done.

You can get a lot of coordination and discussion done with github if your audience has any experience with it. I would also recommend taking a look at WikiBooks as a collaboration platform. It works very well for people to outline and discuss course outlines, module topics, when to use each of the various lesson types, etc, and then you can link all the resulting lessons back in.

**Comment by kantord** [comment]
@wikey thanks for you comment!

I *do* think that GitHub could partially be a platform. For example, we could use it to store the most basic meta data about each course, as those would rarely have to edited, and thus could be done by developers. It could initially also be used for discussions.

I am not a bit fan of the idea of using git for most of the actual course content though, and for these reasons

> Let git worry about it. If the files are small enough, then the conflicts will be easy to resolve

> You can get a lot of coordination and discussion done with github if your audience has any experience with it.

The problem isn't necessarily that the conflicts would be complicated to resolve, but that they have to be resolved at all.

It would be great to assume that the audience has experience with git and github. I think it could be a limiting factor for those who wish to contribute to the courses.

**Comment by kantord** [comment]
Some more details the explain why I don't think git is the ideal way.

I think an ideal system would

- Never "block" the system or accumulate conflicts
- Limit the number of edits that actually end up released
- Minimize the chance of 2 people making conflicting edits

## Never "block" the system or accumulate conflicts

This is because conflicts are not always trivial to resolve, and resolving the conflict might involve non obvious decisions. For example if a skill is limited to 5 words, currently has 4 and two separate edits, then the conflict resolution would involve splitting the skill in two separate skills.

In such a situation, we'd either have to leave both changes aside, and accumulate even more conflicts to it until someone fixes it, or we'd have to block the whole editor until it's fixed. I think none of those are ideal situation if you consider that most people who work on the course would not be developers, would not work on it full time, and would not always have a broad understanding of the whole course. They might just be fixing a typo.

## Limit the number of edits that actually end up released

What I mean by this is that we should not spam the released version of the course. We should prioritize changes that make significant improvements. If the already existing skills change excessively without a real benefit, it would result in a bad experience for learners, as it would impair the process of spaced repetition.

## Minimize the chance of 2 people making conflicting edits

This could be achieved by constructing the course of small enough units

**Comment by kantord** [comment]
> think about Wikipedia's WikiProjects

I have to look this up, but I do agree that we need some soft of system where the structural aspects of the course could be discussed and decided. This platform could be loosely coupled with the course editor, and could be a 3rd party solution

**Comment by kantord** [comment]
The way I imagine it is that branching would not be allowed. Instead, there would be a single, linear "tape" of changes. 2 people would rarely edit at the same time, and if such edit happens, the issues could be still resolved by manually creating a 3rd edit that includes both changes.

**Comment by kantord** [comment]
All that being said, I'm still flirting with the idea of just using git, because that solution would be delightfully simple.

**Comment by wikey** [comment]
The [WikiHistory Project](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_History) seems like a reasonably put together one. 

My main suggestion is that your high-level goals can _either_ be addressed by an ideal technical solution or by general discussion/planning among the collaborators working on the project. For example, if you want to avoid conflicts, you could just say that the process for editing a lesson is: 0) check if anyone has listed themselves as "editing" the lesson on the WikiProject(etherpad/Google Doc/external tool of choice), 1) mark yourself as "editing" it, 2) make your changes

Building anything like a full language course, let alone courses for multiple levels, is a large collaborative project so you are going to absolutely need a place/tool for people to plan, discuss, outline, and coordinate. If you need that anyway, why not put time into getting it off the ground and see just how many of these editing and backend issues can be taken care of before they ever get to the actual lesson building infrastructure?

**Comment by kantord** [comment]
@wikey can you tell me more about how Wikipedia projects are organized? Is there a hierarchical organizational structure, where there is a "boss" who can override individual decisions? 

I would say if there's a team of motivated people with a hierarchical structure with a qualified person on the top, then even with the current course editor (which is fully featured in terms of editing the course data) could go a long way.

What is remarkable about Wikipedia to me is that you can contribute to any wiki article without having been interviewed and accepted into a project, and you can still make a meaningful contribution. And wikipedia is still able to keep the number of inaccuracies low.

**Comment by kantord** [comment]
>  If you need that anyway, why not put time into getting it off the ground and see just how many of these editing and backend issues can be taken care of before they ever get to the actual lesson building infrastructure?

@wikey can you tell me more about how you imagine this?

This is roughly what I have in my head:

- Design a simple YAML schema for course content
- Write a simple script which can convert this human readable format into the format the frontend consumes
- Try running the frontend with it
- Invite people to edit the course and see what happens

**Comment by wikey** [comment]
Like basically everything on Wikipedia, the WikiProjects are self-organized and tend to use consensus-based decision making. Someone puts together some ideas, they all use the talk pages to discuss things, people debate back and forth if there are disagreements, and then everyone works on what they want to. If you want something a _little_ more managed, you can take a look at WikiBooks, which has a separate feature where pages can be reviewed: https://en.wikibooks.org/wiki/Using_Wikibooks/Reviewing_Pages Of course, depending on who you have working on things, you could also just throw people at a google doc. Communicating and collaboration are hard problems but they are ones with lots of software behind them you can just use to see what fits for your community of contributors.

We started working on an Elementary Spanish language textbook on WikiBooks as a way for our non-developer contributors to be able to outline the whole course and simply plug in the interactive lessons where they made sense: https://en.wikibooks.org/wiki/Elementary_Spanish  I think that was our most successful effort at getting actual structured content where individual lessons combined into something larger. Even that was incredibly tough because you have to build the whole thing from scratch.

If I were doing everything over, I would just fork this https://www.laits.utexas.edu/fi/home (basically the only freely licensed modern language textbook I am aware of) and build an interactive workbook to support the whole thing using the audio/video lesson types. Have that plugged into spaced repetition and you will have something that a) provides immediate value to teachers/students and b) gives you a foundation you can fork for other languages so contributors are focused on localizing and adapting a fully functional course rather than having to sit down and write a book. We spent most of a decade trying to get from functioning technology to valuable educational content, without success. Once you have teachers and students using the tool to actually teach/learn a language, you will be able to quickly iterate on the technology.

**Comment by kantord** [comment]
> If I were doing everything over, I would just fork this https://www.laits.utexas.edu/fi/home (basically the only freely licensed modern language textbook I am aware of) and build an interactive workbook to support the whole thing using the audio/video lesson types

That looks like a wonderful resource! I like the license too, it's I think what would be ideal for LibreLingo courses anyway.

I think the fact that we're not supporting everything that they have is also ok, it might be still possible to import at least the vocabulary sections, which would at least give us a framework.

I noticed that the vocabulary sections have examples like this:

```
Je suis étudiant en ... (français, maths, etc.)
```

We would have to replace those with more concrete examples, such as

```
Je suis étudiant en biologie.
```

That's something we'd have to do manually before the course would be even remotely usable, but then it could be a good starting point. We could even use [Tatoeba](https://tatoeba.org/eng/sentences/search?query=Je+suis+%C3%A9tudiant+en&from=und&to=und) for inspiration with the sentences + getting [real audio](https://github.com/kantord/LibreLingo/issues/714#issuecomment-697820797). So we wouldn't be limited to re-using the original audios.

I am also increasingly liking the idea of using French, because there's a lot of people interested in contributing to a French course. Plus I don't speak French, so I could dog-food the course, and also I wouldn't be really able to work on the course, so I'd be forced to involve others from the very beginning

**Comment by LucasCTN** [comment]
Just to keep note because it seems relevant to the conversation: there is a extension to collect structured data on MediaWiki that maybe could work in this kind of project. [Wikibase](https://www.mediawiki.org/wiki/Wikibase), that powers [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page) (see an example of an structured object [here](https://www.wikidata.org/wiki/Q2)).

I don't know if it would work perfectly, but maybe the course editor could be the frontend and a Wikibase instance could be the backend through its API. It has an history and protection systems just like Wikipedia. [Miraheze](https://miraheze.org/) is a free wikifarm with no ads that installs a Wikibase instance automatically if it needed.

In that way, LibreLingo could work as a wiki community that discusses and builds the courses, while having the average user interact with the reactive frontend. But I guess this is kinda of a dramatically different vision for the project?

[Cargo](https://www.mediawiki.org/wiki/Extension:Cargo) is another extension that permits collection of structured data, but I'm not that familiar with.

**Comment by kantord** [comment]
@LucasCTN I like the idea of using Wikimedia, because it's an established platform and also free software. But I wonder if it would have issues? What happens when a broken structure is submitted? With the git idea, it's possible to set up a continuous integration system that would not let a change be merged if it's invalid or doesn't meet certain constraints.

**Comment by LucasCTN** [comment]
> @LucasCTN I like the idea of using Wikimedia, because it's an established platform and also free software. But I wonder if it would have issues? What happens when a broken structure is submitted? With the git idea, it's possible to set up a continuous integration system that would not let a change be merged if it's invalid or doesn't meet certain constraints.

MediaWiki comes with a patrolling system in which people that has patrolling rights can mark certain edits as reviewed and keeps a log with who patrolled which edit. Maybe only previously patrolled edits can be deployed to the website?

It also has filtering system in which you put some rules (I think it's regex) and the system can block an edit and keeps a log of what happened.

The extension FlaggedRevs also can be used, in which a new edit from most is always hidden from public view into a list so users with reviewing rights can review it. Once approved, the edit becomes the new status quo for the page.

Unfortunately I don't know how these systems interact with Wikibase, since I only used them with articles on Wikipedia, so testing would be needed.

**Comment by wikey** [comment]
Re MediaWiki: You could have your CI infrastructure treat patrolled or FlaggedRev MediaWiki changes as PRs, test them normally, and then flag on the Wiki page any edits that fail. MediaWiki is bot-friendly and there are additional resources for formal testing if you go with one of the structured data elements (see for instance this document on developing integrations/plugins for Semantic MediaWiki: https://www.semantic-mediawiki.org/wiki/Help:Programmer%27s_guide).

Re the French book: In addition to the vocabularly, you also get the scaffolding of when concepts and structures get introduced, how much to focus on which features of the language, etc. My guess is that, once you sketch everything our, the total audio you need for all the sentences/phrases in the book is going to be something like <30min. Which basically means you could get audio options from any and all of the Native French speakers who are interested in participating. 

@LucasCTN are those extensions something you can enable as part of one of the existing Wikimedia projects (WikiBook or Wikiversity, etc) or are you thinking about something self-hosted?

**Comment by LucasCTN** [comment]
> @LucasCTN are those extensions something you can enable as part of one of the existing Wikimedia projects (WikiBook or Wikiversity, etc) or are you thinking about something self-hosted?

I thought about creating a self-hosted instance of a LibreLingo wiki and installing those same extensions from WikiBooks and Wikiversity on it. Or maybe use the Miraheze wiki farm as a host for the wiki (it comes with a panel to auto-install those two extensions (FlaggedRevs and Wikibase) completely painless. But then you lose a bit of the control of the settings of the wiki to a third party.

**Comment by kantord** [comment]
>  But then you lose a bit of the control of the settings of the wiki to a third party.

If we don't really need access to those settings, that could be OK, no?

But we do need a way to create regular backups of the content, in a format that we can host in a git repo. This would be necessary for 2 reasons:

- In case Miraheze goes offline, we still need to be able to set up the self-hosted instance and not start from 0
- We don't want to create unnecessary hurdles to forking the project. If someone needs to create a fork, they should also have access to the data in a convenient format

**Comment by LucasCTN** [comment]
> But we do need a way to create regular backups of the content, in a format that we can host in a git repo.

At the very least, MediaWiki offers a way to [import and export](https://www.mediawiki.org/wiki/Manual:Importing_XML_dumps) individual or group of pages as XML, with their history and authors. It won't export site-related settings though, so that would require a database dump and would need some communication with Miraheze.

But I completely agree that regular backup is very important to keep the service running smoothly.

**Comment by kantord** [comment]
I created a draft for a proposed yaml format for writing courses: https://github.com/kantord/LibreLingo/pull/755

I'd appreciate some early feedback :pray: If the format is considered viable, I'll proceed by adding some minimal tooling so that we can actually load the courses in the frontend.

The idea is that this format would permit both humans and computers to work with it. There could be git bots and CI checks for example. It would also be the lowest level non-platform specific format. It could be exported into the frontend app, or for example into a PDF using some HTML templates using weasyprint.

So the data flow would roughly look like this:

`YAML` :arrow_right:  `JSON + Images + Audio` :arrow_right:   `FE APP`

After this, we could still put mediawiki or custom build GUI behind it, so that data flow looks like this


`MediaWik`i  :arrow_right: `YAML` :arrow_right: `JSON + Images + Audio` :arrow_right:   `FE APP`

**Comment by kantord** [comment]
Ok, update on this. Now contribution to the YAML based courses through GitHub is more or less up and running: https://github.com/kantord/LibreLingo/tree/master/docs/courses

Hopefully this is a good first step towards making LibreLingo truly community-owned.

**Comment by LucasCTN** [comment]
> Ok, update on this. Now contribution to the YAML based courses through GitHub is more or less up and running: https://github.com/kantord/LibreLingo/tree/master/docs/courses
> 
> Hopefully this is a good first step towards making LibreLingo truly community-owned.

Are the YAML files already being used to build the courses in the code, or is this a task to be done?

**Comment by kantord** [comment]
> Are the YAML files already being used to build the courses in the code, or is this a task to be done?

they are! well, the Spanish course hasn't been converted yet, so technically the YAML courses aren't going into production yet, but I'm already working on that: https://github.com/kantord/LibreLingo/pull/1020
